version: "3"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo-toronto-dev
    ports:
      - "27017:27017"

  redis:
    image: "redis:latest"
    container_name: redis-toronto-dev
    ports:
      - "6379:6379"

networks:
  my-network:

volumes:
  cassandra-data:
