version: "3"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo-toronto-dev
    ports:
      - "27017:27017"

  cassandra:
    image: cassandra
    restart: always
    container_name: cassandra-toronto-dev
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER}
      - CASSANDRA_DC=${CASSANDRA_DC}
      - CASSANDRA_RACK=${CASSANDRA_RACK}
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:

networks:
  my-network:
